### ISSUE TITLE
Remaining improvements of the new error reporting API

### ISSUE THREAD

**Issue by Nicoretti** [exasol/error-reporting-python#22]
## Summary
For the initial refactoring creating the new error reporting API left a few issue (old and new) open.
This issues shall be addressed in this ticket.

## Tasks

* [ ] Update README/documentation with usage of new API
* [ ] Make sure new API test are executed within the CI
* [ ] Add support for reporting errors related to the `error-reporting` library itself, see also:
        - [FIXME](https://github.com/exasol/error-reporting-python/blob/9486161054b269bce3e5fe24282056ee0105a6f9/exasol/error/_error.py#L78)
        - [makred unit tests](https://github.com/exasol/error-reporting-python/blob/9486161054b269bce3e5fe24282056ee0105a6f9/test/unit/error_test.py#L68)
* [ ] Improve string formatting and output, see also [here](https://github.com/exasol/error-reporting-python/blob/9486161054b269bce3e5fe24282056ee0105a6f9/exasol/error/_error.py#L47).
