### ISSUE TITLE
Add additional warning and error checks to the ExaError validator

### ISSUE THREAD

**Issue by Nicoretti** [exasol/error-reporting-python#23]
## Summary
Currently the error parser only supports basic validity checks. 
Adding more and more precise errors and warnings will help users of the tool to identify issues in their code faster.

## Tasks
* Additional warnings
   - [ ] mitigation defines a placeholder, but no parameter is provided
   - [ ] error defines a parameter, but it is never used
 * Additional errors
    - [ ] check for invalid error code format
