### ISSUE TITLE
Improve usability of generate command by reflecting data from `pyproject.toml` by default

### ISSUE THREAD

**Issue by Nicoretti** [exasol/error-reporting-python#24]
## Summary
Due to the fact that all of our python projects use poetry, it would greatly simplify usage of the `generate` command
if all relevant data can be reflected from the `pyproject.toml` by default.

## Tasks
- [ ] Derive python files from pyproject.toml package definition
- [ ] Derive name form pyproject.toml
- [ ] Derive version from pyproject.toml
