### ISSUE TITLE
Add support for named parameters for error construction

### ISSUE THREAD

**Issue by Nicoretti** [exasol/error-reporting-python#25]
## Summary
Add support for named parameters for error construction.

Example's:

All parameters are named:
```python
error = error.ExaError(
    code="E-TEST-2",
    message="Fire in the server room",
    mitigations=[
        "Use the fire extinguisher",
        "flood the room with halon gas (Attention: be sure no humans in the room!)"
    ],
    parameters={}
)
```
Some parameters are named:
```python
error = error.ExaError(
   "E-TEST-2",
    "Fire in the server room",
    mitigations=[
        "Use the fire extinguisher",
        "flood the room with halon gas (Attention: be sure no humans in the room!)"
    ],
    parameters={}
)
```

## Details
- Only support `code` and `message` as positional or keyword arguments.
- Enforce `keyword` arguments for everything after `message`
- Also let the parser add defaults for missing `keyword` arguments after `message`

## TODO's
- [ ] Add support for named parameters
- [ ] Add test for named parameters
- [ ] Add additional examples of usage to user guide
- [ ] Add note to change-log that this is a breaking change in regard of the `ExaError` calls.
- [ ] Document support for named parameters
